name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKER_PASS: ${{ secrets.DOCKERHUB_PASS }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag luisapolanco/express-randomquotes:latest

    - name: Docker Push
      run: docker push luisapolanco/express-randomquotes
